-- local ls = require("luasnip")
-- ls.add_snippets("markdown", {
-- 	ls.parser.parse_snippet('pagebreak', '<div style=\"page-break-after: always\"></div>'),
-- })
-- 
-- ls.add_snippets("markdown", {
-- 	ls.parser.parse_snippet('center', "<center>\n$1\n</center>")
-- })
-- 
-- ls.add_snippets("markdown", {
-- 	ls.parser.parse_snippet('fraction', "\\displaystyle\\frac{$1}{$2}$3")
-- })
-- 
-- ls.add_snippets("markdown", {
-- 	ls.parser.parse_snippet('integral', "\\displaystyle\\int_{$1}^{$2}$3")
-- })
-- 
-- ls.add_snippets("markdown", {
-- 	ls.parser.parse_snippet('text', "\\text{$1}$2")
-- })
-- 
-- ls.add_snippets("markdown", {
-- 	ls.parser.parse_snippet('implies', "\\implies")
-- })
-- 
-- ls.add_snippets("markdown", {
-- 	ls.parser.parse_snippet('math', "$$1$")
-- })
-- 
-- ls.add_snippets("markdown", {
-- 	ls.parser.parse_snippet('sqrt', "\\sqrt{$1}$2")
-- })
